### ISSUE TITLE
Button which acts as link as a "no reaction area"

### ISSUE THREAD

**Issue by beyer-johannes** [antify/antify-ui#39]
The red marked part is clickable and reacts with a route forwarding as a user expects:

![Image](https://user-images.githubusercontent.com/18086044/184122529-b2118fb5-1128-4c5c-8317-52e7911c720a.png)

All between the red area and the button does not react if the user clicks on it.

This happens when the html is following:

<AntButton>
    <NuxtLink :to="...">Here</NuxtLink>
</AntButton>

Please let discuss a solution. I whould not only remove the padding inside the AntButton because this breaks the UI templating posibillity

**Comment by ThomasKro** [comment]
Ant-Button does now accept "to" like the normal router-link or nuxt-link directive. It will dynamicly transform itself into an a-tag if provided. Style is the same as normal button if nothing else is provided.
