### ISSUE TITLE
Media - Default image for PDF not working

### ISSUE THREAD

**Issue by beyer-johannes** [antify/antify-ui#42]
There is no default image showing for PDF-Types

![image](https://user-images.githubusercontent.com/18086044/190621076-9f8a5e4a-1c83-4379-ad09-d967b6f903de.png)

**Comment by ThomasKro** [comment]
Added the possibility to automatically see the file type if no icon is provided. The directive will look for a title or type attribute and use default icons as necessary.

Default icons: faFile, faFilePdf, faFileImage
