### ISSUE TITLE
Dynamic autofocus for input fields

### ISSUE THREAD

**Issue by beyer-johannes** [antify/antify-ui#44]
The default html attribute "autofocus" just work on initial pageload. If the elements shows up after a page redirect, the autofous will not work.

This case is already catched from vue an a simply solution provided. We should provide this functionality by default.

https://vuejs.org/guide/reusability/custom-directives.html#introduction

**Comment by ThomasKro** [comment]
v-focus is not a default directive from vue 3, you need to implement that yourself (differences between vue and nuxt).
